name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 'Build and Deploy to Cloud Run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Verificar arquivos no diretório
        run: ls -la

      - name: Enable Docker Buildx
        run: docker buildx create --use

      - name: Build and Push Docker Image
        run: docker buildx build --platform linux/amd64 --push -t us-central1-docker.pkg.dev/possible-byway-452305-h4/my-repo/api-service:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy api-service \
            --image us-central1-docker.pkg.dev/possible-byway-452305-h4/my-repo/api-service:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars PORT=8080
 