name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 'Build and Deploy to Cloud Run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Debug Docker Build Command
        run: echo "docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/api-service:latest ."


      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/api-service:latest .

      - name: Push Docker Image to Google Artifact Registry
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/api-service:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy api-service \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/api-service:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars PORT=8080
